#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: brianrestrepo98/djangoappforgithubactions:v1
        ports:
        - containerPort: 8000
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000